import type { PostType } from "../type/types";


export const mockPosts: PostType[] = [
    {
        id: 1028,
        title: "이번 학기 캡스톤 프로젝트 팀원을 구합니다",
        writer: "김민준",
        date: "2026-09-16",
        numRecommend: 7,
        content: "이번 학기 캡스톤 프로젝트를 함께 진행할 팀원을 모집합니다. 주제는 학교 시설 예약 및 대여 서비스를 통합해서 관리할 수 있는 웹 서비스입니다. 프론트엔드는 React와 TypeScript를 사용할 예정이고, 맡은 역할에 책임감을 가지고 참여해주실 분이면 좋겠습니다. 관심 있으신 분들은 댓글이나 쪽지로 연락 부탁드립니다.",
        likedUsers: ["junho", "seoyeon", "minsu", "admin", "hyunjin", "jiwoo", "jimin"],
    },
    {
        id: 1027,
        title: "React에서 상태 관리 라이브러리 꼭 필요한가요?",
        writer: "이서연",
        date: "2026-09-15",
        numRecommend: 3,
        content: "최근 React를 공부하면서 Context API와 useReducer를 사용해 간단한 게시판을 만들어보고 있습니다. 그런데 프로젝트 규모가 커지면 Redux나 Zustand 같은 별도의 상태 관리 라이브러리를 사용하는 것이 좋다는 이야기를 많이 봤습니다. 실제 프로젝트에서는 어느 정도 규모부터 라이브러리를 도입하는지 궁금합니다. 경험 있으신 분들의 의견 부탁드립니다.",
        likedUsers: ["minjun", "hyejin", "donghyun"],
    },
    {
        id: 1026,
        title: "도서관 열람실 좌석 관련 문의드립니다",
        writer: "박지훈",
        date: "2026-09-15",
        numRecommend: 1,
        content: "도서관 열람실을 이용하다가 궁금한 점이 있어서 글을 작성합니다. 현재 좌석을 이용한 뒤 자리를 비울 때 별도의 퇴실 처리를 하지 않아도 되는지 궁금합니다. 장시간 자리를 비워두는 경우가 종종 보이는데, 혹시 좌석 이용 규정이 따로 있다면 알려주시면 감사하겠습니다.",
        likedUsers: ["admin"],
    },
    {
        id: 1025,
        title: "TypeScript 타입 좁히기 관련 질문입니다",
        writer: "최유진",
        date: "2026-09-14",
        numRecommend: 5,
        content: "TypeScript를 공부하면서 union type과 type narrowing 부분에서 조금 헷갈리는 부분이 있습니다. 특히 null이나 undefined가 포함된 데이터를 조건문으로 검사했을 때 TypeScript가 타입을 자동으로 좁혀주는 원리가 궁금합니다. 단순히 문법으로 외우기보다는 실제로 어떤 방식으로 동작하는지 이해하고 싶은데 좋은 예제가 있다면 공유 부탁드립니다.",
        likedUsers: ["minjun", "soobin", "taeyang", "admin", "jisu"],
    },
    {
        id: 1024,
        title: "학과 홈페이지 개선 아이디어를 받고 있습니다",
        writer: "정현우",
        date: "2026-09-13",
        numRecommend: 12,
        content: "현재 학과 홈페이지에서 불편했던 점이나 추가되었으면 하는 기능이 있다면 자유롭게 의견을 남겨주세요. 학생들이 자주 사용하는 공지사항, 강의실 정보, 장비 대여, 세미나실 예약 등의 기능을 조금 더 편리하게 이용할 수 있도록 개선하는 것을 목표로 하고 있습니다. 작은 의견이라도 실제 서비스 개선에 도움이 될 수 있으니 많은 참여 부탁드립니다.",
        likedUsers: ["admin", "jihoon", "minjun", "seoyeon", "yuna", "hyunjin", "jinho", "sumin", "donghyun", "jiwoo", "minseo", "taehyun"],
    },
    {
        id: 1023,
        title: "노트북 구매하려고 하는데 개발용으로 어떤 게 좋을까요?",
        writer: "한지민",
        date: "2026-09-12",
        numRecommend: 4,
        content: "이번에 학교에서 사용할 노트북을 새로 구매하려고 합니다. 주로 VS Code에서 React와 TypeScript를 사용하고 가끔 Python으로 백엔드 공부도 할 예정입니다. 게임이나 영상 편집은 거의 하지 않아서 개발 환경이 원활하게 돌아가는 정도면 충분할 것 같습니다. 예산은 150만원 정도로 생각하고 있는데 비슷한 용도로 사용하고 계신 분들의 추천을 받고 싶습니다.",
        likedUsers: ["seungwoo", "jiyoon", "admin", "minho"],
    },
    {
        id: 1022,
        title: "이번 주 금요일 개발 스터디 모집합니다",
        writer: "오준혁",
        date: "2026-09-11",
        numRecommend: 6,
        content: "매주 금요일 저녁에 진행할 개발 스터디 인원을 모집합니다. 이번 주에는 JavaScript의 비동기 처리와 Promise, async/await를 중심으로 공부할 예정입니다. 발표 형식으로 진행하기보다는 각자 공부한 내용을 공유하고 서로 질문하는 방식으로 진행하려고 합니다. 개발 공부를 꾸준히 하고 싶은 분이라면 전공이나 학년에 관계없이 참여하셔도 됩니다.",
        likedUsers: ["hyunjin", "jisu", "minjun", "sora", "admin", "junho"],
    },
    {
        id: 1021,
        title: "교내 와이파이 접속이 계속 끊기는 것 같습니다",
        writer: "윤도현",
        date: "2026-09-10",
        numRecommend: 0,
        content: "오늘 오전부터 교내 와이파이를 사용하고 있는데 몇 분 간격으로 연결이 끊겼다가 다시 연결되는 현상이 반복되고 있습니다. 다른 분들도 같은 문제를 겪고 계신지 궁금합니다. 노트북과 휴대폰 모두 동일한 현상이 발생하고 있어서 개인 기기의 문제는 아닌 것 같은데 확인 부탁드립니다.",
        likedUsers: [],
    },
    {
        id: 1020,
        title: "백엔드 공부 순서에 대해서 질문드립니다",
        writer: "강수빈",
        date: "2026-09-09",
        numRecommend: 8,
        content: "프론트엔드 개발을 공부하다가 백엔드에도 관심이 생겨서 공부를 시작하려고 합니다. 현재 Python 문법은 어느 정도 알고 있고 FastAPI를 사용해서 간단한 CRUD API를 만들어보려고 합니다. 이후에는 데이터베이스와 SQLAlchemy, 인증과 같은 내용을 공부하려고 하는데 이런 순서로 공부해도 괜찮을까요? 백엔드 공부를 먼저 해보신 분들의 조언을 듣고 싶습니다.",
        likedUsers: ["minjun", "jiyoon", "seoyeon", "admin", "junhyuk", "jihoon", "sumin", "hyunwoo"],
    },
    {
        id: 1019,
        title: "축제 기간 동아리 부스 운영 안내",
        writer: "배지훈",
        date: "2026-09-08",
        numRecommend: 15,
        content: "다음 주 축제 기간 동안 학생회관 앞에서 동아리 부스를 운영합니다. 간단한 게임과 체험 프로그램을 준비하고 있으며 참여하신 분들께 소정의 상품도 드릴 예정입니다. 운영 시간은 오전 11시부터 오후 5시까지이며 점심시간에도 운영할 예정입니다. 많은 관심과 참여 부탁드립니다.",
        likedUsers: ["minseo", "jimin", "yuna", "jiwoo", "admin", "seungmin", "soobin", "junho", "minho", "hyunjin", "sora", "jisu", "taeyang", "donghyun", "jinho"],
    },
    {
        id: 1018,
        title: "Git에서 브랜치 관리 어떻게 하고 계신가요?",
        writer: "김도윤",
        date: "2026-09-07",
        numRecommend: 2,
        content: "팀 프로젝트를 진행하면서 Git 브랜치를 어떻게 나누는 게 좋을지 고민하고 있습니다. 지금은 각자 feature 브랜치를 만들고 작업이 끝나면 develop에 merge하는 방식으로 진행하고 있는데, 프로젝트 규모가 커지면서 브랜치가 많아지고 관리가 조금 어려워졌습니다. 다른 팀에서는 어떤 방식으로 브랜치를 관리하는지 궁금합니다.",
        likedUsers: ["admin", "minjun"],
    },
    {
        id: 1017,
        title: "오늘 수업에서 배운 내용을 정리해봤습니다",
        writer: "김하은",
        date: "2026-09-05",
        numRecommend: 9,
        content: "오늘 수업에서 배운 내용을 복습하면서 개인적으로 정리해봤습니다. 단순히 강의 내용을 옮겨 적기보다는 제가 이해한 방식으로 다시 설명해보려고 했습니다. 혹시 잘못 이해한 부분이 있다면 댓글로 알려주시면 감사하겠습니다. 다른 분들도 공부하면서 정리한 자료가 있다면 함께 공유해주시면 좋을 것 같습니다.",
        likedUsers: ["jisu", "seoyeon", "minjun", "sumin", "admin", "hyunjin", "jihoon", "yuna", "junho"],
    },
];
